### PR TITLE
Fix to covar to patch build error bug found via #110

### PR DESCRIPTION
**Pull request by ntwong0**

### CODE REVIEW

**Comment by ntwong0** [comment]
Do we have a protocol on merging pull request? I'm defaulting to "requester cannot merge." Also listed @menson168 as reviewer since he found the issue.

**Comment by drofp** [comment]
@ntwong0 Feel free to squash and merge as soon as @menson168 has approved the changes. Guidelines are documented here: https://github.com/SJSU-AD/FusionAD/wiki/Contributing

**Review by menson168 — APPROVED** [review]

**Comment by menson168** [comment]
Closes #110

**Comment by drofp** [comment]
@ntwong0 this is ready for merge

**Comment by ntwong0** [comment]
I'm gonna squash and merge, but if this adversely affects file structure (I've had previous experiences where squash and merge doesn't play well with subtree), then I'll revert.

**Comment by ntwong0** [comment]
Looks like we're good!

**Pull request merged**
