### PR TITLE
Iss 172

### LINKED ISSUE #172: Simplify Geodesy Conversion between ENU and Geodetic
For ease of validation from pose estimates to latitude/longitude

### PR DESCRIPTION
**Pull request by drofp**
closes #172 

@joeyzhu00 @menson168  please try this script and get familiar with it for conversion validation. I am submitting this PR early, before comprehensive testing, so I can get some feedback on usability and potential issues.
*Hint:* Feel free to use the following command to get comfortable:
```
python validate_enu_to_latlon.py --help
```

Here are some sample commands to validate North Garage and ATM data, respectively: 
https://docs.google.com/document/d/1OAul-bN8GBPBdft7e7LdhYbYKdU_C60-5O5AoCFdqtY/edit
**NOTE:** Don't forget to replace the path to the bag file with the correct path on your machine. There is an option to search for the file in a file explorer window if you don't provide a path through the command line option.

Here are my results from validating North Garage data with this script:
*GPS data converted from ENU to lat/lon:*
image
*Path data converted from ENU to lat/lon:*
image

Filtering frequency is set to the default (100) so at least the number of points in the path make sense since there are 292 points in the path for the ATM data from Jan10 (the file `/home/drp/bagfiles/jan10/run1_north_garage_straight_pgain1-0_dgain1-0_2019-01-10-21-25-53.bag` on my machine), and ceiling(292/3) = 3

### CODE REVIEW

**Comment by drofp** [comment]
@joeyzhu00 @menson168 if there is anything at all that you find confusing about usage or could use some clarity, please let me know. This is for you guys to use so it shouldn't be a hassle on your end.

**Comment by drofp** [comment]
Here is the result of validating the first few points from the joy run around in a U-Turn from January 4th, for reference:
image

**Comment by drofp** [comment]
Also, the `validate_geodesy_conversion.py` is just a renamed old file. I'm not sure why it didn't get recorded as renamed, but just note that the marked changes to code in that file were not made under this PR.

**Review by joeyzhu00 — APPROVED** [review]
Looks clear and straight forward to use!

**Comment by menson168** [comment]
geo_validation
Is there a reason why the Initial Alt, Lat, Long are separated (lat and long only). Aside from that, I think you are good to merge after the order is fixed.

**Comment by drofp** [comment]
@menson168 nice catch! i was iterating through a dictionary earlier, so the iteration order was arbitrary. It's now standardized in sorted order as so:
image

**Comment by drofp** [comment]
Also the output file location of the '.txt' GPSVisualizer files is now in ```/geodesy/geodesy_data/data_validation/``` to stay consistent with the other validation files

**Pull request merged**
