### PR TITLE
Iss 246

### PR DESCRIPTION
**Pull request by joeyzhu00**
image
With a waypoint acceptance zone of 2.5 radians.

### CODE REVIEW

**Comment by menson168** [comment]
Can you find a way so that the waypoint sits on top of the visualization?

**Review by menson168 — CHANGES_REQUESTED** [review]
Can you find a way so that the waypoint sits on top of the donut visualization?

**Comment by joeyzhu00** [comment]
> Can you find a way so that the waypoint sits on top of the donut visualization?

image
I changed the A in the RGBA values that are configurable in the launch file

**Review by menson168 — APPROVED** [review]

**Review by menson168 — CHANGES_REQUESTED** [review]
The vehicle would only consider points that are in the front, which means the donut (whether it is empty or filled) should be readjusted to only the front 180 degrees of the half dome.

**Review by menson168 — CHANGES_REQUESTED** [review]
Can you migrate the visualizer under the utility module? You can create a catkin_pkg called 'visualizer'. The /src should be exclusively for codes that are absolutely critical to the operation of the vehicle.

**Comment by menson168** [comment]
@joeyzhu00 Did you run this visualizer with point cloud data as well? How does the donut rings differentiate from the point cloud?

**Comment by joeyzhu00** [comment]
> @joeyzhu00 Did you run this visualizer with point cloud data as well? How does the donut rings differentiate from the point cloud?

I can change the opaqueness of the rings as well so they don't cover up the pointcloud points. I will change and test with point cloud data tomorrow.

**Comment by joeyzhu00** [comment]
> Can you migrate the visualizer under the utility module? You can create a catkin_pkg called 'visualizer'. The /src should be exclusively for codes that are absolutely critical to the operation of the vehicle.

Sure.

**Comment by menson168** [comment]
> > @joeyzhu00 Did you run this visualizer with point cloud data as well? How does the donut rings differentiate from the point cloud?
> 
> I can change the opaqueness of the rings as well so they don't cover up the pointcloud points. I will change and test with point cloud data tomorrow.

Sounds good. Let's keep this PR open and review again after more testing tomorrow.

**Comment by joeyzhu00** [comment]
> The vehicle would only consider points that are in the front, which means the donut (whether it is empty or filled) should be readjusted to only the front 180 degrees of the half dome.

image
Changed the parameter in the control launch file

**Comment by joeyzhu00** [comment]
> Can you migrate the visualizer under the utility module? You can create a catkin_pkg called 'visualizer'. The /src should be exclusively for codes that are absolutely critical to the operation of the vehicle.

Migrated files to `visualization` under the `utility` folder

**Review by menson168 — APPROVED** [review]

**Pull request merged**
