### PR TITLE
Iss 202 - Arduino CAN Gateway

### LINKED ISSUE #202: Ardu-CAN gateway
Creation of an Arduino based CAN-ROS gateway.

### PR DESCRIPTION
**Pull request by menson168**
Please refer to the readme in ```FusionAD/arduino/can_gateway``` for now. Once this is finalized and tested, I will copy the README over to the wiki.

Like I said in #202 , disregard the file changes for the testing and data collection stuff.

closes #202

### CODE REVIEW

**Review by joeyzhu00 — COMMENTED** [review]
Was the code tested on the car? There's way too much on here to review. Your header file is near the top of the list but I cannot find the actual `.ino` file where the Arduino does the work. I assume you followed the timing scheme used in `can_control_adapter.py` from `ISS-72` and followed the documentation given in the [Drive-by-Wire CAN Bus Documentation](https://docs.google.com/document/d/1plZNmI7Gd_ZMMDmYey83yGkkMNOMN2SwaUVDmy9UbV0/edit) so the code should work.

**Comment by menson168** [comment]
> Was the code tested on the car? There's way too much on here to review. Your header file is near the top of the list but I cannot find the actual `.ino` file where the Arduino does the work. I assume you followed the timing scheme used in `can_control_adapter.py` from `ISS-72` and followed the documentation given in the [Drive-by-Wire CAN Bus Documentation](https://docs.google.com/document/d/1plZNmI7Gd_ZMMDmYey83yGkkMNOMN2SwaUVDmy9UbV0/edit) so the code should work.

Not yet, I plan to do the testing tmr. Follow the [README](https://github.com/menson168/FusionAD/tree/ISS-202/arduino/can_gateway) in the repo, then you will see why I did not develop with Arduino IDE (just so I can have header files and locally referenced libraries, better for multiple host machines). I do agree that there is a lot of code to review. 
Please only review the following for the main gateway logic:
- ```FusionAD/arduino/can_gateway/src/main.cpp```
- ```FusionAD/arduino/can_gateway/include/osv_can_gateway_main.h```

Thanks!

**Review by joeyzhu00 — APPROVED** [review]
Looks good! Timing was correct from testing between the power and the control messages on the SME motor for 0x204 and 0x304 respectively.

**Review by drofp — APPROVED** [review]
I feel like it will be orders of magnitude easier to just test and see if it works. Builds fine on my laptop

**Pull request merged**
