### PR TITLE
Iss 185

### LINKED ISSUE #185: Zero gain issue with control stack and Control Debug Message Cleanup
Control Stack encounters a numerical error when one of the control gain is zero.

### PR DESCRIPTION
**Pull request by menson168**
Closes #185 
Also threw in the Catkin_ignore for the old swift_nav package so most of us won't run into the build error of it.

### CODE REVIEW

**Comment by menson168** [comment]
The code has been fully tested with the following bag (Filtered bag with only topics that are subscribed by the high-level control stack) and no error has been thrown by the control code.

[Link to Bag File](https://drive.google.com/file/d/1eWISx-aOh5_rJqws_eqWjG6lyIJWooMY/view?usp=sharing)

**Review by joeyzhu00 — APPROVED** [review]
Looks good!

**Comment by drofp** [comment]
Closes #185

**Comment by drofp** [comment]
Where is the change that fixed this issue? it looks like it's mainly just adding debug info

**Comment by joeyzhu00** [comment]
> Where is the change that fixed this issue? it looks like it's mainly just adding debug info

The change was made here `src/modules/control/src/lat_controller.cpp`

**Comment by drofp** [comment]
> > Where is the change that fixed this issue? it looks like it's mainly just adding debug info
> 
> The change was made here `src/modules/control/src/lat_controller.cpp`

it looks like there was just stylistic changes and debug info added. What line(s) fixed the issue of encountering the numerical error when one of the control gains is zero (as stated in the referenced issue)?

**Comment by joeyzhu00** [comment]
> > > Where is the change that fixed this issue? it looks like it's mainly just adding debug info
> > 
> > 
> > The change was made here `src/modules/control/src/lat_controller.cpp`
> 
> it looks like there was just stylistic changes and debug info added. What line(s) fixed the issue of encountering the numerical error when one of the control gains is zero (as stated in the referenced issue)?

It's in lines 175-184 of `src/modules/control/src/lat_controller.cpp`

**Comment by menson168** [comment]
Somehow removing some of the conditional statement of the final calculation code eliminated the numerical issue. I guess there was some error in passing data through functions before.

**Comment by drofp** [comment]
Unfiltered steering angle might not ever be assigned properly, causing a divide by zero error here:
image

**Comment by drofp** [comment]
Seems like this will work for now though, as long as we can gaurantee that `unfilteredSteeringAngle` is gauranteed to never be 0 when steering angle is calculated. Might be worth putting in some conditional check before `steeringAngle`'s assignment. I would file a separate issue for that, though. (if it's even necessary)

**Review by drofp — APPROVED** [review]

**Comment by menson168** [comment]
@drofp Good catch on that one. I just pushed a commit which replaces the abs(x)/x method with a standard math library function that can do sign checks safely. Code is tested and stuff.

**Comment by menson168** [comment]
@drofp Good catch on that. I replaced the abs(x)/x method with a standard math lib function that can do sign checks safely. I also make a small change to the steering angle calculation in which I added a small number to the velocity denominator in the Stanley function so it won't encounter numerical error if velocity is zero, that value is supposed to be the "soft gain" in the paper but I will implement that as a function/node parameter in another issue. 

Please let me know if I should merge ahead after your review. Thanks.

**Comment by drofp** [comment]
@menson168 looks good for now! clear for merge

**Pull request merged**
