### PR TITLE
Iss 104

### LINKED ISSUE #104: Control Node Zero Gain Bug
Control node output would become NaN when zero gain is applied to the controller.

### PR DESCRIPTION
**Pull request by menson168**
closes #104 

Tested controller library with gain of zero.

### CODE REVIEW

**Review by drofp — CHANGES_REQUESTED** [review]
Please modify tests to check for reduced precision on floating point values

https://github.com/abseil/googletest/blob/master/googletest/docs/advanced.md#floating-point-macros

**Comment by menson168** [comment]
Modification has been made to testing condition from equal to near. Attached screenshot for test result.

unittest_fix_control_near

PR should be ready to merge, pending approval.

**Comment by drofp** [comment]
@menson168 What is the justification for the two fatal errors that occur when tests are run? I have validated that I can reproduce the same output

**Comment by menson168** [comment]
> @menson168 What is the justification for the two fatal errors that occur when tests are run? I have validated that I can reproduce the same output

That was a test case for NaN handling. When the controller outputs NaN values, it would print FATAL messages to the terminal as a notification to the user. Internally, it would publish "-69" as an error value. Therefore, the fatal messages are expected.

**Review by drofp — APPROVED** [review]

**Pull request merged**
